<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>MediaNotes.LegacyApi</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="4.0.30506" />
    <PackageReference Include="Newtonsoft.Json" Version="4.5.11" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>
</Project>
