CREATE TABLE [dbo].[User] (
    [UserID]                                  INT IDENTITY(10000,1) NOT NULL,
    [CustomerId]                              BIGINT           NULL,
    [FirstName]                               NVARCHAR(70)     NULL,
    [LastName]                                NVARCHAR(70)     NULL,
    [PersonCode]                              VARCHAR(20)      NULL,
	[IsStronglyAuthenticated]                 BIT              NOT NULL DEFAULT(0),
    [BirthDate]                               DATE             NULL,
    [Email]                                   NVARCHAR(100)    NOT NULL,
    [EmailConfirmed]                          BIT              NOT NULL,
    [PhoneNumber]                             NVARCHAR (20)    NULL,
	[PhoneNumberConfirmed]                    BIT              NOT NULL,
    [PasswordHash]                            VARCHAR (70)     NULL,
    [SecurityStamp]                           VARCHAR (64)     NULL,
	[TwoFactorEnabled]                        BIT              NOT NULL,
	[LockoutEndDateUtc]                       DATETIME         NULL,
	[LockoutEnabled]                          BIT              NOT NULL,
	[AccessFailedCount]                       INT              NOT NULL,
	[UserName]                                NVARCHAR (128)   NULL,
    [CreatedDate]                             DATETIME         CONSTRAINT [DF_User_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    --[LastLoginDate]                           DATETIME         NOT NULL,
    --[LastActivityDate]                        DATETIME         NOT NULL,
    --[LastPasswordChangedDate]                 DATETIME         NULL,
    --[LastLockoutDate]                         DATETIME         NULL,
    CONSTRAINT [PK_User_UserID] PRIMARY KEY CLUSTERED ([UserID] ASC),
    CONSTRAINT [UK_User_Email] UNIQUE NONCLUSTERED ([Email] ASC)
);